### ISSUE TITLE
[Question] Multiple tables?

### ISSUE THREAD

**Issue by FarbodSalamat-Zadeh** [jgilfelt/android-sqlite-asset-helper#100]
Is there a way I can access multiple tables from my SQLite database in `assets` in the same class extending `SQLiteAssetHelper` (just as I would be able to with Android's `SQLiteOpenHelper`)?

**Comment by Kisty** [comment]
I have multiple tables but use one `SQLiteAssetHelper`. Just use the same helper object to access multiple tables from the same database. 

The helper object should be for each database in your app, not each table.

**Comment by FarbodSalamat-Zadeh** [comment]
How would I do that?

In the example given in the README file:

```java
public class MyDatabase extends SQLiteAssetHelper {

    private static final String DATABASE_NAME = "northwind.db";
    private static final int DATABASE_VERSION = 1;

    public MyDatabase(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }
}
```

There is no `TABLE_NAME` constant that would reference the name of each table when making calls such as `db.query()`.

Could you give me an example of your implementation?

**Comment by Kisty** [comment]
Do something like:

```
public Cursor getAnimals() {
    return getReadableDatabase().rawQuery("SELECT * FROM animals", null);
}

public Cursor getPets() {
    return getReadableDatabase().rawQuery("SELECT * FROM pets", null);
}
```

That way your accessing multiple tables in one database from assets. I do so in our app.

**Comment by FarbodSalamat-Zadeh** [comment]
Ah, okay - I get it!

Thank you.
