### ISSUE TITLE
SetForcedUpgrade doesn't update database

### ISSUE THREAD

**Issue by mmangliers** [jgilfelt/android-sqlite-asset-helper#101]
My app is still in production, so while the database is being developed I've just been using forced upgrade to copy over the new database; unfortunately, this doesn't seem to be actually overwriting the old database. I will not see the new data unless I uninstall the app before rerunning it from Android Studio.

The database is being copied to the default path, and the helper is being provided through a static singleton pattern. Any thoughts?

**Comment by Kisty** [comment]
Have you incremented the database version number? See https://github.com/jgilfelt/android-sqlite-asset-helper/issues/89

**Comment by mmangliers** [comment]
Yes, totally forgot to include a few more tidbits:

I've incremented the database number, and the log shows that it's starting the forced upgrade and indicates that the copy is complete. However, upon drawing any data from the DB, it's still the old data.

**Comment by Kisty** [comment]
OK. How are you calling setForcedUpgrade()? With a version number or without? Also, try doing the setForcedUpgrade in your helper constructor. That worked for me.

**Comment by mmangliers** [comment]
Tried both to no avail; it's being called in the private constructor. Have a getInstance() method which returns the static instance if it exists or constructs a new one. setForcedUpgrade() is called in that constructor. I'll see about moving it around,

**Comment by mmangliers** [comment]
Weirdly, moving the call to getInstance() seems to have fixed it. No idea why that would make a difference, as it's called at the end of the constructor either way.

**Comment by Kisty** [comment]
Glad you solved it. 

Ah, did you have instant run enabled? I don't think singletons play nice with instant run.

**Comment by mmangliers** [comment]
I was wondering if it might have something to do with instant run, yeah. I'll play around with that as well.
