### ISSUE TITLE
how to copy data from old version db to new

### ISSUE THREAD

**Issue by varshaAv** [jgilfelt/android-sqlite-asset-helper#110]
i am using sqliteasset helper library.using this,i created a tutorial app with 500 questions n answers. and also their is a fav table in which i m saving user inputs.
now i want to add new question in tables other than fav table. but when user will update the app. i dont want to loose the fav tablr data that is user data.so how can i write script for this.? means i want my latest db with user data from old db.

i tried everything.but nothing helps. in some cases i got user data.but the app uses old db.
plz help.i alreadg wasted my 8 hours for this

**Comment by varshaAv** [comment]
and plznote that, i dont to change schema of any table.i just want to update my db withnew rows. and those rows are a bunch of 100-200 records. so i  write insert query through script.
i have already created new updated db file. just tell me, how can i use new db. with old db.fav table. i just want that fav table from old db. all other tables are from new db

**Comment by jon-adams** [comment]
As I understand it, you just need to follow the standard instructions in the documentation for this library on how to use it as normal; create an upgrade script and set a new version number on the DB to have it be applied. And in that script, put your INSERT commands. (There or more details, but they're all covered in the main documentation.)

You say "you've tried everything" but don't list what those attempts were. What _did_ you try that isn't working with that process?

**Comment by varshaAv** [comment]
Thanx for reply sir,
let say i have 2 tables in my pld version db.
1)tutorial table 
2)favourite table

in which, favourite table is for local storage, means it will contain user data.
so after upgrade i want to keep all data that is present in that table.

and the tutorial table is the one, in which i am proving questions,
so now with the new version i want to provide bunch of 500 new questions in it.
so i cant include those insert queries through script upgrade scrfipt . right? coz it will be headache.

so, now
1)i have updated the version number.
2)created the updated .db file with sqlite db browser.
3)added this db file in assets/databases folder with original db name.
4)now my upgrade script looks like this,

//just add one more table with default value 0 into favourite table.
ALTER TABLE "favourites" ADD "updateDb1" INT NOT NULL DEFAULT 0;

ALTER TABLE "tutorial" RENAME TO "temp";
CREATE TABLE "tutorial" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"question"	TEXT NOT NULL,
	"answer"	TEXT NOT NULL,
	"status"	TEXT NOT NULL DEFAULT 'unfav'
);
INSERT INTO "tutorial" ("Id","question","answer","status") SELECT "Id","question","answer","status" FROM "temp";
DROP TABLE "temp";

============
is it correct format of upgrade script?
i saved it as, tutorial.db_upgrade_1-2.sql

actually i didnt understand how to write insert command in it.
because how it works? i dont know.
which table should i rename? the table which available in the user's phone?
or the table that is i am providing through newly updated file in assets folder?

and which record should be copied from and where?

i just want to achive is,
my new updated tables that are available in assets should be updated in user's phone,
but the favourite table shold be used from user's old db., not from db

sorry for confusion, but i will be thankful to you if you help me.
plz.see my upgrade script and just give me one example so that i can understand.

**Comment by varshaAv** [comment]
and when i run the app with above script , android studio throws exception...like cant upgrade read only database from version one to two.

**Comment by varshaAv** [comment]
and when i run the app with above script , android studio throws exception...like cant upgrade read only database from version one to two.

**Comment by jon-adams** [comment]
What is the exact error message and stack you get about "can't upgrade read only database"?

Regarding your other questions, this library only deals with running the script at the appropriate times for you. If you need general help on how to write SQL commands, there are lots of sites, tutorials, and guides available elsewhere on general SQL programming.

**Comment by varshaAv** [comment]
right now i dont have my laptol with me, but will you plz explain, how can i differentiate beetween old db and new db table while writing insert query. have you seen my script? is it written in right way?

**Comment by varshaAv** [comment]
right now i am not able to show you my exact error but below i am showing the example (i copied and pasted from google)

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.calvert.adam.lolinformer/com.calvert.adam.lolinformer.championsActivity}: android.database.sqlite.SQLiteException: Can't upgrade read-only database from version 1 to 2: /data/data/com.calvert.adam.lolinformer/databases/champions.db

I am getting error similar to this.

**Comment by jon-adams** [comment]
That error doesn't have to do with this library. You might be opening it with `getReadableDatabase` or you have CREATE commands where you shouldn't, etc. Unfortunately, we can't help you with Android SQL issues here. Just if you have problems with this library not running the scripts at the right time.

**Comment by varshaAv** [comment]
means you are saying my script is written in right format?

**Comment by varshaAv** [comment]
butcan you explain? when wewrite insert query in script... then insert into tablename... here in this line first table nae reffers to which table? and following select from tablename refers to which table? old or newdb? how this library works in upgrading?

**Comment by jon-adams** [comment]
The "format" is just SQL commands. Nothing special about them. So yeah, SQL command, semi-colon, line break, and repeat, is fine. Like any other SQL script. All this library does is break them up by semi-colon, then pass them as regular, raw SQL commands to the engine.

**Comment by varshaAv** [comment]
no i am not getting how it works... i have confusion in how to refer correct table in query

**Comment by varshaAv** [comment]
can i use getWritableDatabase with this library?

**Comment by varshaAv** [comment]
yes finally got solution to my problem.on google o found somewhere that this library currently doesnt support feature of coppying data from new db to old db.so i need to add every new insert statement in upgrade script

**Comment by varshaAv** [comment]
please if possible add new feature for this, its just a suggestion because on google their are lots of people who are finding solution for this

**Comment by Kisty** [comment]
The way I do a partial upgrade is have two databases. One for the bundled
data, the other for user data. Then use this library to handle the data
updates by using `setForcedUpgrade` which overwrites the old database with
the new one. It won't work with your current solution so you may need to
change it if you want. Took a while to work out how to connect the two
(`ATTACH DATABASE` command) but it's doable and has been in production for
4 years!
