### ISSUE TITLE
Can this work if the compressed database file is larger than 1 MB?

### ISSUE THREAD

**Issue by rkiddy** [jgilfelt/android-sqlite-asset-helper#74]
If my database, compressed, is over 1 MB in size, I understand that I cannot have that in the assets folder. I must chop the file up. Then the helper class can cat the fragments together to re-create the larger file. But this does not work for me.

Can this work using this code? I do not see it mentioned by the documentation.

See: https://github.com/rkiddy/android-database-first-loading

**Comment by mnjrupp** [comment]
I'm using this with a 25mb file. No issues at all.


Sent by Outlook for Android





On Thu, Sep 10, 2015 at 5:11 PM -0700, "Ray Kiddy" <notifications@github.com> wrote:
If my database, compressed, is over 1 MB in size, I understand that I cannot have that in the assets folder. I must chop the file up. Then the helper class can cat the fragments together to re-create the larger file. But this does not work for me.

Can this work using this code? I do not see it mentioned by the documentation.

See: https://github.com/rkiddy/android-database-first-loading

---
Reply to this email directly or view it on GitHub:
https://github.com/jgilfelt/android-sqlite-asset-helper/issues/74

**Comment by rkiddy** [comment]
Well, yes, my file is over 3 MB and it works fine. I guess I should not have assumed there would be a problem. :-)
