### ISSUE TITLE
gradle:2.2.0-alpha3

### ISSUE THREAD

**Issue by terrakok** [jgilfelt/android-sqlite-asset-helper#98]
For new gradle plugin (classpath 'com.android.tools.build:gradle:2.2.0-**alpha3**')
android.database.sqlite.SQLiteDatabase.getVersion() crashed with null pointer exception

**Comment by Kisty** [comment]
Have you done a clean build? In Android Studio do `Build` -> `Clean`

Looks like your database is null. What device shows this crash? Can you post the full stack trace?

**Comment by terrakok** [comment]
I found it. It's gradle:2.2.0-alpha3 bug!
http://blog.goddchen.de/2016/06/android-gradle-plugin-2-2-0-alpha3-is-missing-zipalign/
